# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Add.ui'
#
# Created by: PySide6 UI code generator
#
# WARNING: Any manual changes made to this file will be lost when pyside6-uic is
# run again.  Do not edit this file unless you know what you are doing.

from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Add(object):
    def setupUi(self, Add):
        Add.setObjectName("Add")
        Add.resize(259, 357)
        Add.setMinimumSize(QtCore.QSize(259, 357))
        Add.setMaximumSize(QtCore.QSize(259, 357))
        self.label = QtWidgets.QLabel(Add)
        self.label.setGeometry(QtCore.QRect(10, 10, 54, 16))
        self.label.setObjectName("label")
        self.printId = QtWidgets.QLineEdit(Add)
        self.printId.setGeometry(QtCore.QRect(80, 40, 171, 31))
        self.printId.setObjectName("printId")
        self.Hint1 = QtWidgets.QTextEdit(Add)
        self.Hint1.setGeometry(QtCore.QRect(10, 160, 241, 191))
        self.Hint1.setObjectName("Hint1")
        self.UserGroup = QtWidgets.QComboBox(Add)
        self.UserGroup.setGeometry(QtCore.QRect(0, 40, 71, 31))
        self.UserGroup.setObjectName("UserGroup")
        self.UserGroup.addItem("")
        self.UserGroup.addItem("")
        self.AddButton1 = QtWidgets.QPushButton(Add)
        self.AddButton1.setGeometry(QtCore.QRect(170, 80, 75, 24))
        self.AddButton1.setObjectName("AddButton1")
        self.createButton1 = QtWidgets.QPushButton(Add)
        self.createButton1.setGeometry(QtCore.QRect(170, 120, 75, 24))
        self.createButton1.setObjectName("createButton1")

        self.retranslateUi(Add)
        QtCore.QMetaObject.connectSlotsByName(Add)

    def retranslateUi(self, Add):
        _translate = QtCore.QCoreApplication.translate
        Add.setWindowTitle(_translate("Add", "Add User and Group"))
        self.label.setText(_translate("Add", "Search"))
        self.UserGroup.setItemText(0, _translate("Add", "User"))
        self.UserGroup.setItemText(1, _translate("Add", "Group"))
        self.AddButton1.setText(_translate("Add", "Add"))
        self.createButton1.setText(_translate("Add", "Create"))