# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConnectToServer.ui'
#
# Created by: PySide6 UI code generator
#
# WARNING: Any manual changes made to this file will be lost when pyside6-uic is
# run again.  Do not edit this file unless you know what you are doing.

from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(320, 499)
        Dialog.setMinimumSize(QtCore.QSize(320, 0))
        Dialog.setMaximumSize(QtCore.QSize(320, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.udpButton = QtWidgets.QPushButton(Dialog)
        self.udpButton.setObjectName("udpButton")
        self.horizontalLayout.addWidget(self.udpButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.ServerTable = QtWidgets.QTableWidget(Dialog)
        self.ServerTable.setObjectName("ServerTable")
        self.ServerTable.setColumnCount(3)
        self.ServerTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.ServerTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ServerTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ServerTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.ServerTable)
        self.Hint = QtWidgets.QPlainTextEdit(Dialog)
        self.Hint.setObjectName("Hint")
        self.verticalLayout.addWidget(self.Hint)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Connect = QtWidgets.QPushButton(Dialog)
        self.Connect.setObjectName("Connect")
        self.horizontalLayout_2.addWidget(self.Connect)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.Disconnect = QtWidgets.QPushButton(Dialog)
        self.Disconnect.setObjectName("Disconnect")
        self.horizontalLayout_2.addWidget(self.Disconnect)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 5)
        self.verticalLayout.setStretch(3, 2)
        self.verticalLayout.setStretch(4, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "ConnectToServer"))
        self.udpButton.setText(_translate("Dialog", "Send a UDP Boardcast"))
        item = self.ServerTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ServerID"))
        item = self.ServerTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Feature"))
        item = self.ServerTable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "FeaturePort"))
        self.Connect.setText(_translate("Dialog", "Connect"))
        self.Disconnect.setText(_translate("Dialog", "Disconnect"))