# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InvitePopUp.ui'
#
# Created by: PySide6 UI code generator
#
# WARNING: Any manual changes made to this file will be lost when pyside6-uic is
# run again.  Do not edit this file unless you know what you are doing.

from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(230, 158)
        self.InviteText = QtWidgets.QLabel(Dialog)
        self.InviteText.setGeometry(QtCore.QRect(10, 20, 211, 41))
        self.InviteText.setObjectName("InviteText")
        self.YesButton = QtWidgets.QPushButton(Dialog)
        self.YesButton.setGeometry(QtCore.QRect(10, 110, 75, 24))
        self.YesButton.setObjectName("YesButton")
        self.NoButton = QtWidgets.QPushButton(Dialog)
        self.NoButton.setGeometry(QtCore.QRect(130, 110, 75, 24))
        self.NoButton.setObjectName("NoButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "INVITE_GROUP"))
        self.InviteText.setText(_translate("Dialog", "TextLabel"))
        self.YesButton.setText(_translate("Dialog", "Yes"))
        self.NoButton.setText(_translate("Dialog", "No"))