# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModifyGroup.ui'
#
# Created by: PySide6 UI code generator
#
# WARNING: Any manual changes made to this file will be lost when pyside6-uic is
# run again.  Do not edit this file unless you know what you are doing.

from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(299, 176)
        self.GroupName = QtWidgets.QLabel(Dialog)
        self.GroupName.setGeometry(QtCore.QRect(30, 20, 151, 20))
        self.GroupName.setObjectName("GroupName")
        self.LeaveButton = QtWidgets.QPushButton(Dialog)
        self.LeaveButton.setGeometry(QtCore.QRect(10, 120, 101, 31))
        self.LeaveButton.setObjectName("LeaveButton")
        self.InviteButton = QtWidgets.QPushButton(Dialog)
        self.InviteButton.setGeometry(QtCore.QRect(180, 120, 75, 24))
        self.InviteButton.setObjectName("InviteButton")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(160, 90, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 60, 151, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.GroupName.setText(_translate("Dialog", "GroupName"))
        self.LeaveButton.setText(_translate("Dialog", "Leave Group"))
        self.InviteButton.setText(_translate("Dialog", "Invite"))
        self.label.setText(_translate("Dialog", "Print UserName to Invite"))